CREATE TABLE IF NOT EXISTS device_tokens (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  token       VARCHAR(200) NOT NULL UNIQUE,
  stores      VARCHAR(200) DEFAULT '',
  categories  VARCHAR(500) DEFAULT '',
  watchlist   VARCHAR(500) DEFAULT '',
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_token (token)
);
